name: pull-request
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    branches: [development]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: npm

      - name: Install project dependencies
        run: yarn

      - name: Verify Typescript
        run: yarn tsc
